name: Deploy to EC2
on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Access EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          script_stop: true
          script: |
            cd /home/2024devSpringv3
            git config --global --add safe.directory /home/2024devSpringv3
            sudo git pull origin main
            sudo ./gradlew bootWar
            sudo fuser -l -n tcp 8080
            nohup java -jar build/libs/*SNAPSHOT.war &
            sudo lsof -i:8080